###Get a list of all products
GET http://localhost:4000/products

### Create a product
POST http://localhost:4000/products
Content-Type: application/json

{
  "name": "qbus1",
  "price": 4999
}

### GET a product by id
GET http://localhost:4000/products/645b85783c65bad13f1584c6

### Update a product by id
PATCH  http://localhost:4000/products/645b8f81b5a9f65a42b2164a
Content-Type: application/json

{
  "price": 5999
}


### Delete a product by id
DELETE  http://localhost:4000/products/645b8fe2b5a9f65a42b2164c

### 404 route Not Found
GET http://localhost:4000/645b8fe2b5a9f65a42b2164c

